module.exports = {
  name: 'co-scale-out',
  title: 'Scaling Elastic to 40TB/Day',
  repo: 'wdpitt/co-scale-out',
  gateway: 'https://api.fslides.dev',
  slidesDir: 'slides',

  slides: [
    'cover.html',
    'challenge.html',
    'efficiency.html',
    'status.html',
    'ec2-instances.html',
    'config.html',
    'logsdb.html',
    'tiers.html',
    'metrics.html',
    'ai-assistant.html',
    'workflows.html',
    'after-hours.html',
    'closing.html',
  ],

  labels: [
    'Cover',
    'The Challenge',
    'Efficiency Story',
    'Where We Stand',
    'EC2 Instances Needed',
    'Configuration',
    'LogsDB',
    'Tiered Storage',
    'Metrics & Prometheus',
    'AI Assistant',
    'Workflows',
    'After-Hours Teams',
    'Next Steps',
  ],
};
